version: 2.1
# Use a package of configuration called an orb.
orbs:
 
jobs:    
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Execute cloudfront.yml
          command: |
            aws cloudformation deploy \
             --template-file cloudfront.yml \
             --stack-name production-distro \
             --parameter-overrides PipelineID="mybucket-${CIRCLE_WORKFLOW_ID:0:3}" 
                
   
# Sequential workflow
workflows:
  # Name the workflow
  getLastdeployID:
    jobs:
      - promote_to_production
