version: 2.1
# Use a package of configuration called an orb.
orbs:
 
jobs:    
  deploy_stack: 
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
       - run:
           name: Create Cloudformation Stack
           command: |
             aws cloudformation deploy \
                --template-file cloudfront.yml \
                --stack-name production-distro \
                --parameter-overrides PipelineID="production-bucket198287506099" \
                
  create_and_deploy_front_end:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
       - run:
           name: Execute bucket.yml - Create Cloudformation Stack 
           command: |
             aws cloudformation deploy \
                --template-file bucket.yml \
                --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID} \
                --parameter-overrides MyBucketName="mybucket-${CIRCLE_WORKFLOW_ID}"
       # Uncomment the step below if yoou wish to upload all contents of the current directory to the S3 bucket
       # - run: aws s3 sync . s3://mybucket-${CIRCLE_WORKFLOW_ID:0:7} --delete
                
   
# Sequential workflow
workflows:
  # Name the workflow
  myDeploystack:
    jobs:
      - deploy_stack
      - create_and_deploy_front_end
