version: 2.1
# Use a package of configuration called an orb.
orbs:
 
jobs:    
  deploy_stack: 
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
       - run:
           name: Create Cloudformation Stack
           command: |
             aws cloudformation deploy \
                --template-file cloudfront.yml \
                --stack-name production-distro \
                --parameter-overrides PipelineID="production-bucket198287506099" \ # Name of the S3 bucket you created manually.
                
   
# Sequential workflow
workflows:
  # Name the workflow
  myDeploystack:
    jobs:
      - deploy_stack

